version: '3.4'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  golangsocial:
    image: golangsocial
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "dynamodb-local"

    environment:
      AWS_ACCESS_KEY_ID: 'local'
      AWS_SECRET_ACCESS_KEY: 'local'
      AWS_REGION: 'us-east-1'
      DYNAMODB_ENDPOINT: 'http://dynamodb-local:8000'
      JWT_SECRET: 'prl@+_rAwrlmLd_rEseKAjOb-NL+=PofIF6*VU-RlJ-D6_BeCap7StA0IhabrEN&'

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
